/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package freereport;

import java.awt.Component;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author miro_
 */
public class Accountant extends javax.swing.JFrame {
    private Acc ac=new Acc();
    private DefaultTableModel tb;

    /**
     * Creates new form Accountant
     */
    public Accountant() {
        initComponents();
        showa();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Students_Table = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CK_DueFee = new javax.swing.JButton();
        Add_St = new javax.swing.JButton();
        Edit_St = new javax.swing.JButton();
        Search_St = new javax.swing.JButton();
        Delete_St = new javax.swing.JButton();
        Log_Out = new javax.swing.JButton();
        Exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Students_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "First Name", "Last Name", "Grade", "DueFee"
            }
        ));
        jScrollPane1.setViewportView(Students_Table);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                .addContainerGap())
        );

        CK_DueFee.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CK_DueFee.setText("Change DueFee for Student");
        CK_DueFee.setToolTipText("");
        CK_DueFee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CK_DueFeeActionPerformed(evt);
            }
        });

        Add_St.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Add_St.setText("Add New Student");
        Add_St.setToolTipText("");
        Add_St.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_StActionPerformed(evt);
            }
        });

        Edit_St.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Edit_St.setText("Edit Student");
        Edit_St.setToolTipText("");
        Edit_St.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Edit_StActionPerformed(evt);
            }
        });

        Search_St.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Search_St.setText("Search for Student");
        Search_St.setToolTipText("");
        Search_St.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_StActionPerformed(evt);
            }
        });

        Delete_St.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Delete_St.setText("Delete Student");
        Delete_St.setToolTipText("");
        Delete_St.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_StActionPerformed(evt);
            }
        });

        Log_Out.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Log_Out.setText("LogOut");
        Log_Out.setToolTipText("");
        Log_Out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Log_OutActionPerformed(evt);
            }
        });

        Exit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 387, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(190, 190, 190))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Log_Out, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(CK_DueFee, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Add_St, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Edit_St, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Search_St, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Delete_St, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Search_St, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(Add_St, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(Edit_St, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(Delete_St, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(CK_DueFee, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Log_Out, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CK_DueFeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CK_DueFeeActionPerformed
        // TODO add your handling code here:
        String st=JOptionPane.showInputDialog("Enter Student ID");
        int id=Integer.parseInt(st);
        int ck=ac.chickst(id);
        if(ck==1){
            JOptionPane.showMessageDialog(null,"You Will Change This Student DueFee:\n"+ ac.stDueFee(id));
            String Due=JOptionPane.showInputDialog("Enter Student DueFee");
            int DueFee=Integer.parseInt(Due);
            ac.stChangeDueFee(id, DueFee);
            JOptionPane.showMessageDialog(null,"Student DueFee Changed Successfully");
            ReLoad();
        }
        else
            JOptionPane.showMessageDialog(null, "Student Not Excest");
    }//GEN-LAST:event_CK_DueFeeActionPerformed

    private void Add_StActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_StActionPerformed
        // TODO add your handling code here:
        String fname=JOptionPane.showInputDialog("Enter Student First Name");
        String lname=JOptionPane.showInputDialog("Enter Student Last Name");
        String grade=JOptionPane.showInputDialog("Enter Student Grade");
        double gr=Double.parseDouble(grade);
        String Due=JOptionPane.showInputDialog("Enter Student DueFee");
        int DueFee=Integer.parseInt(Due);
        JOptionPane.showMessageDialog(null, "New Student ID: "+ac.newst(fname, lname, gr, DueFee)+"\nWas Added Successfully");
        ReLoad();
    }//GEN-LAST:event_Add_StActionPerformed

    private void Edit_StActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Edit_StActionPerformed
        // TODO add your handling code here:
        String st=JOptionPane.showInputDialog("Enter Student ID");
        int id=Integer.parseInt(st);
        int ck=ac.chickst(id);
        if(ck==1){
            JOptionPane.showMessageDialog(null,"You Will Change This Student Information:\n"+ ac.StInfo(id));
            String fname=JOptionPane.showInputDialog("Enter Student First Name");
            String lname=JOptionPane.showInputDialog("Enter Student Last Name");
            String grade=JOptionPane.showInputDialog("Enter Student Grade");
            double gr=Double.parseDouble(grade);
            JOptionPane.showMessageDialog(null,ac.editst(id,fname,lname,gr));
            ReLoad();
        }
        else
            JOptionPane.showMessageDialog(null, "Student Not Excest");
    }//GEN-LAST:event_Edit_StActionPerformed

    private void Search_StActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_StActionPerformed
        // TODO add your handling code here:
        String st=JOptionPane.showInputDialog("Enter Student ID");
        int id=Integer.parseInt(st);
        JOptionPane.showMessageDialog(null,ac.StInfo(id));
    }//GEN-LAST:event_Search_StActionPerformed

    private void Delete_StActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_StActionPerformed
        // TODO add your handling code here:
        if(Students_Table.getSelectedRowCount()==1){
            int ra=Students_Table.getSelectedRow();
            int id=(Integer)(Students_Table.getValueAt(ra, 0));
            int ck=ac.chickst(id);
            String info=ac.StInfo(id);
            ac.deletest(id);
            JOptionPane.showMessageDialog(null, info+"\nDeleted Successfully\n");
            ReLoad();
        }
        else{
            JOptionPane.showMessageDialog(null, "Please Select one Student From the Table to Delete");
            Students_Table.clearSelection();
        }
    }//GEN-LAST:event_Delete_StActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        ac.close();
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void Log_OutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Log_OutActionPerformed
        // TODO add your handling code here:
        LogIns logo=new LogIns();
        ac.close();
        logo.setVisible(true);
        close();
    }//GEN-LAST:event_Log_OutActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Accountant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Accountant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Accountant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Accountant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Accountant().setVisible(true);
            }
        });
    }
    public void showa(){
        ArrayList<GetSt> ar=ac.shows();
        tb=(DefaultTableModel)Students_Table.getModel();
        Object s[]=new Object[5];
        for (int i=0;i<ar.size();i++){
            s[0]=ar.get(i).getid();
            s[1]=ar.get(i).getFname();
            s[2]=ar.get(i).getLname();
            s[3]=ar.get(i).getGrade();
            s[4]=ar.get(i).getDueFee();
            tb.addRow(s);
        }
    }
    public void close(){
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    public void ReLoad(){
        tb=(DefaultTableModel)Students_Table.getModel();
        Students_Table.selectAll();
        int count=Students_Table.getSelectedRowCount();
        for(int i=0;i<count;i++){
            tb.removeRow(Students_Table.getSelectedRow());
        }
        showa();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_St;
    private javax.swing.JButton CK_DueFee;
    private javax.swing.JButton Delete_St;
    private javax.swing.JButton Edit_St;
    private javax.swing.JButton Exit;
    private javax.swing.JButton Log_Out;
    private javax.swing.JButton Search_St;
    private javax.swing.JTable Students_Table;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
