/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package freereport;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author miro_
 */
public class AdminFram extends javax.swing.JFrame {

    private Admin ad=new Admin();
    private DefaultTableModel tb;
    /**
     * Creates new form AdminFram
     */
    public AdminFram() {
        initComponents();
        showa();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Accountants_Table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        Search_ac = new javax.swing.JButton();
        Add_New = new javax.swing.JButton();
        Edit_Ac = new javax.swing.JButton();
        Delete_Ac = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        LogOut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        Accountants_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "First Name", "Last Name"
            }
        ));
        jScrollPane1.setViewportView(Accountants_Table);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome");

        Search_ac.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Search_ac.setText("Search For Accountant");
        Search_ac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_acActionPerformed(evt);
            }
        });

        Add_New.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Add_New.setText("Add New Accountant");
        Add_New.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_NewActionPerformed(evt);
            }
        });

        Edit_Ac.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Edit_Ac.setText("Edit an Accountant");
        Edit_Ac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Edit_AcActionPerformed(evt);
            }
        });

        Delete_Ac.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Delete_Ac.setText("Delete an Accountant");
        Delete_Ac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_AcActionPerformed(evt);
            }
        });

        Exit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        LogOut.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LogOut.setText("LogOut");
        LogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Delete_Ac, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Edit_Ac, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Add_New, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Search_ac, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(61, 61, 61)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Search_ac, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(Add_New, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(Edit_Ac, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(Delete_Ac, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 53, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
        ad.close();
    }//GEN-LAST:event_ExitActionPerformed

    private void LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutActionPerformed
        // TODO add your handling code here:
        LogIns logo=new LogIns();
        ad.close();
        logo.setVisible(true);
        close();
    }//GEN-LAST:event_LogOutActionPerformed

    private void Search_acActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_acActionPerformed
        // TODO add your handling code here:
        String st=JOptionPane.showInputDialog("Enter Accountant ID");
        int id=Integer.parseInt(st);
        JOptionPane.showMessageDialog(null,ad.AcInfo(id));
    }//GEN-LAST:event_Search_acActionPerformed

    private void Add_NewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_NewActionPerformed
        // TODO add your handling code here:
        String fname=JOptionPane.showInputDialog("Enter Accounatnt First Name");
        String lname=JOptionPane.showInputDialog("Enter Accountant Last Name");
        String user=JOptionPane.showInputDialog("Enter Accountant User Name");
        String pass=JOptionPane.showInputDialog("Enter Accountant Password");
        JOptionPane.showMessageDialog(null, "New Accountant ID: "+ad.newac(fname, lname, user, pass)+"\nWas Added Successfully");
        ReLoad();
    }//GEN-LAST:event_Add_NewActionPerformed

    private void Edit_AcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Edit_AcActionPerformed
        // TODO add your handling code here:
        String st=JOptionPane.showInputDialog("Enter Accountant ID");
        int id=Integer.parseInt(st);
        int ck=ad.chickac(id);
        if(ck==1){
            JOptionPane.showMessageDialog(null,"You Will Change This Accountant Information:\n"+ ad.AcInfo(id));
            String fname=JOptionPane.showInputDialog("Enter Accountant First Name");
            String lname=JOptionPane.showInputDialog("Enter Accountant Last Name");
            JOptionPane.showMessageDialog(null,ad.editac(id,fname,lname));
            ReLoad();
        }
        else
            JOptionPane.showMessageDialog(null, "Accountant Not Excest");
    }//GEN-LAST:event_Edit_AcActionPerformed

    private void Delete_AcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_AcActionPerformed
        // TODO add your handling code here:
        if(Accountants_Table.getSelectedRowCount()==1){
            int ra=Accountants_Table.getSelectedRow();
            int id=(Integer)(Accountants_Table.getValueAt(ra, 0));
            int ck=ad.chickac(id);
            String info=ad.AcInfo(id);
            ad.deleteac(id);
            JOptionPane.showMessageDialog(null, info+"\nDeleted Successfully\n");
            ReLoad();
        }
        else{
            JOptionPane.showMessageDialog(null, "Please Select one Accountant From the Table to Delete");
            Accountants_Table.clearSelection();
        }
    }//GEN-LAST:event_Delete_AcActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminFram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminFram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminFram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminFram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminFram().setVisible(true);
            }
        });
    }

    public void showa(){
        ArrayList<GetAc> ar=ad.showc();
        tb=(DefaultTableModel)Accountants_Table.getModel();
        Object s[]=new Object[3];
        for (int i=0;i<ar.size();i++){
            s[0]=ar.get(i).getid();
            s[1]=ar.get(i).getFname();
            s[2]=ar.get(i).getLname();
            tb.addRow(s);
        }
    }
    public void close(){
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    public void ReLoad(){
        tb=(DefaultTableModel)Accountants_Table.getModel();
        Accountants_Table.selectAll();
        int count=Accountants_Table.getSelectedRowCount();
        for(int i=0;i<count;i++){
            tb.removeRow(Accountants_Table.getSelectedRow());
        }
        showa();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Accountants_Table;
    private javax.swing.JButton Add_New;
    private javax.swing.JButton Delete_Ac;
    private javax.swing.JButton Edit_Ac;
    private javax.swing.JButton Exit;
    private javax.swing.JButton LogOut;
    private javax.swing.JButton Search_ac;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
